# Generated by Django 5.1 on 2024-09-05 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paitent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='clinicaldata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componentname', models.CharField(choices=[('hw', 'HEIGHT/WEIGHT'), ('bp', 'BLOOD PRESSURE'), ('heatrtrate', 'HEART RATE')], max_length=20)),
                ('componentvalue', models.CharField(max_length=20)),
                ('measuredatetime', models.DateTimeField(auto_now_add=True)),
                ('paitent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicalsApp.paitent')),
            ],
        ),
    ]
